### ISSUE TITLE
ppc64le build

### ISSUE THREAD

**Issue by isuruf** [conda-forge/_openmp_mutex-feedstock#1]
cc @beckermr

**Comment by beckermr** [comment]
Not following, a build for this arch exists already.

**Comment by isuruf** [comment]
I don't see a LLVM build for ppc64le at https://anaconda.org/conda-forge/_openmp_mutex/files

**Comment by beckermr** [comment]
Ack yeah I saw the gnu one.

**Comment by beckermr** [comment]
Yeah ppc64le needs to be added in the conda_forge.yaml

**Comment by beckermr** [comment]
we need llvm-openmp to build the mutex

**Comment by beckermr** [comment]
closed by #2
